name: Start Timer

on:
  issues:
    types: [labeled]

jobs:
  start-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check if label is "in progress"
        if: github.event.label.name == 'in progress'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Label is 'in progress'. Recording start time."
          START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          gh issue edit ${{ github.event.issue.number }} --add-label "started-at-${START_TIME}"
