name: Start Timer

on:
  issues:
    types: [labeled]

jobs:
  start-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Cette action permet de cloner le repository

      # Vous pouvez maintenant exécuter des commandes git ou d'autres actions qui nécessitent un repository Git valide
      - name: Display Git status
        run: git status

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check if label is "in progress"
        if: github.event.label.name == 'in progress'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         echo "Label is 'in progress'. Recording start time."
          START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Check if the label already exists before trying to add it
          if gh issue view ${{ github.event.issue.number }} --label "started-at-${START_TIME}" > /dev/null 2>&1; then
            echo "Label 'started-at-${START_TIME}' already exists."
          else
            gh issue edit ${{ github.event.issue.number }} --add-label "started-at-${START_TIME}"
          fi
