name: Issue Time Tracker

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Track label time
        uses: tbsmcd/label_timer@v3.1
        with:
          start_label: 'in progress'
          stop_label: 'done'
          comment: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
