name: Time Tracking Workflow

on:
  issues:
    types: [labeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Track time
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Installing dependencies..."
          npm install @actions/github @actions/core

          echo "Running the tracking script..."
          node -e "
          const github = require('@actions/github');
          const core = require('@actions/core');
          const context = github.context;

          console.log('Event received:', JSON.stringify(context.payload, null, 2));
          const issue = context.payload.issue;
          const label = context.payload.label.name;

          console.log('Issue:', issue);
          console.log('Label:', label);

          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

          const now = new Date().toISOString();
          console.log('Current time:', now);

          var updatedBody='';
          
          if (label === 'in progress') {
            if(issue.body){
              updatedBody = issue.body + `\nStart Date: ${now}`
            }else{
              updatedBody = `Start Date: ${now}`
            } 
            octokit.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: updatedBody
            }).then(response => {
              console.log('Issue updated successfully:', response.data.html_url);
            }).catch(error => {
              console.error('Error updating issue:', error);
            });
          }
          "
