name: Time Tracking Workflow

on:
  issues:
    types: [labeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if label is 'in progress'
        if: github.event.label.name == 'in progress'
        run: |
          echo "Project: ${{ github.event.repository.name }}"
          echo "Label: ${{ github.event.label.name }}"

      - name: Move card to 'In Progress'
        if: github.event.label.name == 'in progress'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: 'track-time-workflow'
          column: 'In progress'
          repo-token: ${{ secrets.TOKEN }}
        
