name: Issue Time Tracker

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Track label time
        uses: tbsmcd/label_timer@v3.1
        with:
           targets: 'in progress, review, done'
           token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
