name: Issue Time Tracker

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Track label time
        uses: tbsmcd/label_timer@v3.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          start-label: 'in progress'
          stop-label: 'review'
          comment: true  # Add a comment with the time spent when the stop-label is applied
