name: Time Tracking Workflow

on:
  issues:
    types: [labeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is 'in progress'
        if: github.event.label.name == 'in progress'
        run: |
          echo "Label is 'in progress', proceeding with the workflow...
      - name: Debug GitHub Project and Column
        if: github.event.label.name == 'in progress'
        run: |
          echo "Project: ${{ github.event.repository.name }}"
          echo "Label: ${{ github.event.label.name }}"

      - name: Move card to 'In Progress'
        if: github.event.label.name == 'in progress'
        uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: track-time-workflow
          column: In progress
          repo-token: ${{ secrets.TOKEN }}
