name: Start Timer

on:
  issues:
    types: [labeled]

jobs:
  start-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Cette action permet de cloner le repository

      # Vous pouvez maintenant exécuter des commandes git ou d'autres actions qui nécessitent un repository Git valide
      - name: Display Git status
        run: git status

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Add comment to issue
        if: github.event.label.name == 'in progress'
        run: |
          echo "Adding comment to issue..."
          CURRENT_DATE=$(date -u +"%d/%m/%Y à %H:%M")
          gh issue comment ${{ github.event.issue.number }} --body "Commencez le ${CURRENT_DATE}"
