name: Timer
on:
  # Issue のラベルを対象とする場合
  issues:
    types:
      ['labeled', 'unlabeled']
  # Pull Request のラベルを対象とする場合
  pull_request:
    types:
      ['labeled', 'unlabeled']
jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - name: test_run
        uses: tbsmcd/label_timer@v2.2
        id: test_run
        with:
          # ラベルはカンマ区切りで複数指定できます。
          targets: 'in progress, review, done'
          token: ${{ secrets.GITHUB_TOKEN }}
      # 計測結果を後の steps で利用したい場合
      - name: checkout
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == 'in progress' }}
        uses: actions/checkout@v2
      - name: add_time_label
        if: ${{ github.event.action == 'unlabeled' && github.event.label.name == 'review' }}
        # outputs は以下の変数として取得できます。
        #
        # `github.event.action == labeled` の場合
        # ${{ steps.test_run.outputs.url }} 対象になった Issue or Pull Request の URL
        #
        # `github.event.action == unlabeled` の場合
        # ${{ steps.test_run.outputs.url }} 対象になった Issue or Pull Request の URL
        # ${{ steps.test_run.outputs.passed_seconds }} ラベルが付与されてから削除されるまでの秒数
        # ${{ steps.test_run.outputs.sum_seconds }} ラベルが付与されてから削除されるまでの秒数（合計）
        run: |
          pip install requests
          python .github/example.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.issue.url }} ${{ steps.test_run.outputs.sum_seconds }}
