name: Time Tracking Workflow

on:
  issues:
    types: [labeled]

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if label is 'in progress'
        if: github.event.label.name == 'in progress'
        run: |
          echo "Project: ${{ github.event.repository.name }}"
          echo "Label: ${{ github.event.label.name }}"

      - name: Move Issues To Project Column
        uses: fojia/action-move-issues-to-column@v1.0.2
        with:
          project: 'track-time-workflow'          
          column: 'In progress'
          owner: 'sha-zha'
        
